### PR TITLE
intro screen created

### PR DESCRIPTION
**Pull request by venkey-dev**
new intro classes and XML layouts.
Intro Activity, intro class, and introSliderAdapter are new Kotlin files. activity_intro and intro_slider are 2 new XML layouts and intro_selector, intro_screen_background, and intro_screen_background are new drawable. new colors were added and themes are set to orange themes in dark and night themes.

### CODE REVIEW

**Comment by ConnectBhawna** [comment]
Kindly share the demo showing app is correctly working

**Comment by venkat-clone** [comment]
https://user-images.githubusercontent.com/51732590/184497851-76d934c9-ae35-4ecc-9701-fdd97e0677e0.mp4

**Comment by venkey-dev** [comment]
https://user-images.githubusercontent.com/51732590/184497974-8a348175-7631-4be7-984b-674effaf7ecc.mp4

**Comment by ConnectBhawna** [comment]
Looking cool to me.
Thanks for contributing

**Pull request merged**
